### ISSUE TITLE
Question xelatex compilation

### ISSUE THREAD

**Issue by yusie1978** [wengan-li/ncku-thesis-template-latex#24]
Hi, 
could you help me of how to solve this problem? I try to compile thesis using xelatex in my laptop, but these error messages are shown...

![xelatex](https://user-images.githubusercontent.com/13177534/30124844-131a9ad4-9369-11e7-9e14-06d975476aa5.JPG)

**Comment by wengan-li** [comment]
Mmmmm.....

I haven't a guaranty answer for this one right now.

Could you send me part of your codes for testing ?
Please provide following file structure:
```
thesis
  - conf/...
  - template/...
  - thesis.tex
```

Meanwhile, could you try to update latest of MiKTex ?

**Comment by wengan-li** [comment]
I am not able to recreate the environment that Win XP with MikTex,
the MikTex now shows 'SSL connect error',
and I am not able to solve this yet.

**Comment by yusie1978** [comment]
Yes, me too, have the problem with SLL connect error.
I try to update and install new version of Miktex (from Miktex 2.9.4248 change to basic miktex 2.9.6361), but now it's not working anymore, even for other latex files.

**Comment by wengan-li** [comment]
Sadly,
I tried update XP to SP3 and updated all the patch from Auto Update, it still show the SSL connect error.
 [This bug is mention at the maillist](https://sourceforge.net/p/miktex/bugs/2548/), someone said install the SSL certificates or set the environment variable works on Windows XP.
I tried but still got the error.

After that I installed `basic-miktex-2.9.6361-x64.exe` in a latest update Windows 7 which works fine.

Although I think you can install old version of MikTex (maillist mention `2.9.6100` should be fine) to try bypass this problem. But in longer term the updater of MikTex will still also update MikTex itself,
which eventually I think you will back to `2.9.6361` and meet the problem again.
This may become a unsolvable problem in XP.

You was mentioned [the reason of using XP](https://github.com/wengan-li/ncku-thesis-template-latex/issues/17#issuecomment-234831911) is because of the microcontrollers.
I assumes you will need to use USB to control it.
So I suggest you use another machine with Win 7 (or later version) to bypass this problem.
If you don't want another one, try to install [VirtualBox](https://www.virtualbox.org/wiki/Downloads) and install Win 7 as guest OS.

**Comment by yusie1978** [comment]
Thank you,

I have installed miktex 2.9.6022 and it looks fine. I try to install the old version of thesis template.. right now, i use template 1.5.1.

**Comment by wengan-li** [comment]
I tried `template v1.5.2` in Win 7 with `basic-miktex-2.9.6361-x64.exe` and Texmaker USB version `5.0.2` (and `4.5`), and it compiled without any error.
I really think your problem is caused by XP or MikTex (or both).

**Comment by wengan-li** [comment]
Good, at least you got a workable version back to work first.

**Comment by yusie1978** [comment]
Yes, I can work with my IEEE paper and books, but still not working with dissertation's templates.
Firstly, I test my xelatex to compile the original template from version 1.4.8 to 1.5.1 but none of them works.
I still got these messages. 

![xelatex](https://user-images.githubusercontent.com/13177534/30247004-1ac3c726-963c-11e7-9915-f6480f3a52cf.JPG)

**Comment by yusie1978** [comment]
I have tried again and again, and it seems the text and contents look fine, except for the cover like so:
![xelatex](https://user-images.githubusercontent.com/13177534/30247434-4aa912ba-9647-11e7-8e23-1d0603ddc654.JPG)

**Comment by wengan-li** [comment]
There is a big file structure change from `1.4.8` to `1.5.x`, I was told you [don't update the template](https://github.com/wengan-li/ncku-thesis-template-latex/issues/20#issuecomment-267352880) if you don't need to.

I apologize that and suggest you should based on template `1.5.x` and copy and paste from `1.4.8` the needed contents and file.
Base on the design, you should only copy the whole `thesis/context` directory and part of the data from file `thesis/conf/conf.tex` in your `1.4.8` to the `thesis/conf/conf.tex` in template `1.5.x`.
After that this should work as well.

**Comment by wengan-li** [comment]
@yusie1978 Do your migration works fine ?

**Comment by yusie1978** [comment]
No, still not working. Right now I just type it, and if i want to compile in a full version, I will do it in different machine like in other PC  (not in laptop).

**Comment by wengan-li** [comment]
it has passed a month, I hope your way of switching machine to type it that work fine.

**Comment by yusie1978** [comment]
Yes, it's been a month.. Right now i just use the new machine with windows 7 installed. It's been ok. I am planning to remove my Wibdows XP in my laptop, just use Windows 7.

**Comment by wengan-li** [comment]
:) Problem solved.

**Comment by wengan-li** [comment]
From my personal experience, I will recommend you update to Win 10.

Because I discovered Win 10 is much more simplify on driver installing than Win 7,
which Win 7 is always require you to provide installer of the driver.
So it is good for install Win 10 on an old machine than the Win 7.

Also mainstream support of Win 7 is ended on January 13, 2015 [(from Wiki)](https://en.wikipedia.org/wiki/Windows_7).
It seem Win 7 is being outdating.
