### ISSUE TITLE
Unable to compile the files in June 2019

### ISSUE THREAD

**Issue by wengan-li** [wengan-li/ncku-thesis-template-latex#39]
Unable to compile the source v1.5.6
```
OS: Windows 10 1803
Editor: Texmaker 5.0.3
Miktex: 2.9.7100 (11 June 2019) with latest update (16 June 2019)
Template: v1.5.6
```

---

Error Message
![Screenshot 2019-06-16 at 12 05 27 PM](https://user-images.githubusercontent.com/6211564/59558899-0e57ab80-902f-11e9-93b6-a22582ed1202.png)

---

Possible Reason
```
1. Miktex's XeLaTex is newer that Template's coding, maybe some LaTex coding is changed.
2. Some package version is upgraded.
```

**Comment by ygLinc9012** [comment]
Excuse me, after completed all the modifications.
Does that make it impossible to compile?

Are you willing to try to separate the questions one by one?
Because i test the [problem ](https://github.com/wengan-li/ncku-thesis-template-latex/pull/38) and it is fine in my environment.

Currently my version is:
OS: Windows 10
Editor: Texmaker 5.0.3
Miktex: 2.9 latest update (5 June 2019)
Template: v1.5.6

If you need any help, please let me know.

**Comment by wengan-li** [comment]
Sorry I am not so sure your meanings of `Does that make it impossible to compile?`.

The design of the template is all modifications (update or delete) will try to not affect existing user (such as you right now).
Except for some big changes have been made to fix a bug or a feature becoming meanings.
This kind of change which writes into ChangeLog and notices to you guy as possible.

Sure. No problem.
Just this issue causing unable to check and update the code.
So I can't do anything right now.

Your report is very useful.
At least the template should be workable (otherwise I wouldn't release it as a stable version).
So that I think I stack into a setup problem again (or some kind of setting).
This happens sometime before, so this is normal for me.

Thank you very much.
Just continue your own work first.
I will update you when I am ready.

**Comment by wengan-li** [comment]
Suddenly all thing works again........
Really don't know why.
